# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true // deprecated

# Setup
title:               Monster Brain Dev Blog
tagline:             'Game Dev. Web Dev. Hobbyist.'
description:         'A personal dev blog of monster brain a.k.a <a href="https://github.com/monsterbrain">Faisal Rasak. Mainly blogs about short solutions, ideas and work in progress stuffs. If time permits.'
url:                 http://monsterbrain.github.io
baseurl:             'http://monsterbrain.github.io/'
paginate:            5

# About/contact
author:
  name:              Faisal Rasak
  url:               https://twitter.com/faisal_rasak
  email:             monsterkillu@gmail.com

# Custom vars
version:             1.0.0
